# Site settings
title: "多想，想深，所想"
author: "Deep Thinker"
description: "多想，想深，所想"
keywords: "Software Engineering, Mathematics, Philosophy"
biography:新能源"
 created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://thinkdeep.github.io"

twitter_username: 
github_username: thinkdeep
google-analytics: UA-69060-5

simple_search: http://baidu.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
pygments: true
