# Site settings
title: "多想，想深，所想"
author: "Deep Thinker"
description: "这是一个是用 <a href='http://jekyllrb.com/'Jekyll</a>引擎，托管在 <a href='https://pages.github.com/'>Github Pages</a>上的博客"
keywords: "Software Engineering, Mathematics, Philosophy"
biography: "一个半资深新能源行业从业者，搞过技术，搞过商务，搞过投资，搞过女人。"

baseurl: ""
url: "http://thinkdeep.github.io"

twitter_username: Deep Thinker
github_username: thinkdeep
google-analytics: UA-69060-5

simple_search: http://baidu.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
pygments: true
